version: '3.8'

services:

  mariadb:
    image: mariadb:latest
    container_name: messenger_backend
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: toDoList_db
      MYSQL_USER: dummy@localhost.com
      MYSQL_PASSWORD: dummy_password
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  flask:
    build: ./backend
    container_name: flask_app
    environment:
      FLASK_APP: 'app.py'
      FLASK_ENV: 'development'
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
